In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('dataset.csv')
df

                                    town      area   price
0             Township             26000   25000.0  550000
1            Township              26000       NaN  555000
2               Township           26000   30000.0  555500
3                           west windsor   35000.0  600000
4    west windsor                  26000   24000.0  650000
5                   west windsor   26000  400000.0  655000
6                   west windsor   26000   50000.0  655500
7                robinsville       26000   29000.0  700000
8             Robinsville          26000   31000.0  750000
9             Robinsville          26000   26000.0  750500
10             Robinsville         26000   32000.0  750550
11           Robinsville           26000   42000.0  800000

In [20]:
mean = df['area'].mean()

In [21]:
df['area'] = df['area'].fillna(mean)

In [22]:
df

                                    town           area   price
0             Township             26000   25000.000000  550000
1            Township              26000   65818.181818  555000
2               Township           26000   30000.000000  555500
3                           west windsor   35000.000000  600000
4    west windsor                  26000   24000.000000  650000
5                   west windsor   26000  400000.000000  655000
6                   west windsor   26000   50000.000000  655500
7                robinsville       26000   29000.000000  700000
8             Robinsville          26000   31000.000000  750000
9             Robinsville          26000   26000.000000  750500
10             Robinsville         26000   32000.000000  750550
11           Robinsville           26000   42000.000000  800000

In [24]:
dummies = pd.get_dummies(df.town)
dummies

,Township 26000,west windsor 26000,Robinsville 26000,Robinsville 26000,Robinsville 26000,Township 26000,Township 26000,robinsville 26000,west windsor,west windsor 26000
0,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,True,False
4,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,True,False,False
8,False,False,False,True,False,False,False,False,False,False
9,False,False,False,True,False,False,False,False,False,False
10,False,False,False,False,True,False,False,False,False,False
11,False,False,True,False,False,False,False,False,False,False

In [ ]:
merged = pd.concat([df, dummies], axis='column')